name: qr_code_example
description: Flutter project for demonstrating QR Code example.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.0.12
  cached_network_image: ^2.0.0
  path_provider: ^1.6.0
  flutter_share: ^1.0.2+1
  permission_handler: '^4.2.0+hotfix.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true